language: "ru" # language code for launching pretrained asr
transcription_dir_path: "" # path to the directory where transcription txt files will be created
true_transcription_dir_path: "" # path to the directory with transcriptions
wav_dir_path: "" # path to the directory with wav files to transcribe